# Computes GC_VERSION_STRING and writes include/gc/Version.h into BUILD_DIR.
# Called at build time via add_custom_target.
#
# Required inputs: PROJECT_SOURCE_DIR, BUILD_DIR, GIT_EXECUTABLE, VERSION_CODE

set(sfx "")

if(GIT_EXECUTABLE AND EXISTS "${PROJECT_SOURCE_DIR}/.git")
  execute_process(
    COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD
    WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
    OUTPUT_VARIABLE hash
    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)

  execute_process(
    COMMAND ${GIT_EXECUTABLE} ls-files --modified --others --exclude-standard
    WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
    OUTPUT_VARIABLE dirty1
    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)

  execute_process(
    COMMAND ${GIT_EXECUTABLE} diff --name-only --cached
    WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
    OUTPUT_VARIABLE dirty2
    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)

  set(dirty_content "")
  if(dirty1 OR dirty2)
    set(dirty_list)
    if(dirty1)
      string(REPLACE "\n" ";" dirty1_list "${dirty1}")
      list(APPEND dirty_list ${dirty1_list})
    endif()
    if(dirty2)
      string(REPLACE "\n" ";" dirty2_list "${dirty2}")
      list(APPEND dirty_list ${dirty2_list})
    endif()
    list(REMOVE_DUPLICATES dirty_list)
    list(SORT dirty_list)
    foreach(f ${dirty_list})
      if(EXISTS "${PROJECT_SOURCE_DIR}/${f}")
        file(READ "${PROJECT_SOURCE_DIR}/${f}" c)
        string(APPEND dirty_content "${c}")
      else()
        string(APPEND dirty_content "-${f}")
      endif()
    endforeach()
  endif()

  if(dirty_content)
    string(SHA1 dirty_hash "${dirty_content}")
    set(sfx "${hash}-${dirty_hash}")
  elseif(hash)
    set(sfx "${hash}")
  endif()
endif()

if(sfx)
  set(version_string "${VERSION_CODE}-${sfx}")
else()
  set(version_string "${VERSION_CODE}")
endif()

set(content
    "// Auto-generated by cmake/version.cmake - do not edit.
#pragma once

#define GC_VERSION_CODE ${VERSION_CODE}
#define GC_VERSION_STRING \"${version_string}\"
")
set(out "${BUILD_DIR}/include/gc/Version.h")
if(EXISTS "${out}")
  file(READ "${out}" existing)
  if(existing STREQUAL content)
    return()
  endif()
endif()
file(MAKE_DIRECTORY "${BUILD_DIR}/include/gc")
file(WRITE "${out}" "${content}")
