//===-- Cache.h - Compiled binaries cache -----------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
#pragma once

#include <array>
#include <cstring>
#include <memory>
#include <utility>
#include <variant>

#include "gc/Utils/Misc.h"
#include "gc/Version.h"

#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/SHA1.h"

#include "gc/ExecutionEngine/JitEngine.h"

#include "mlir/IR/BuiltinOps.h"
#include "mlir/Interfaces/DataLayoutInterfaces.h"

using namespace mlir;

namespace mlir::gc::cache {

struct CachedEngine {
  std::unique_ptr<::gc::JitEngine> engine;
  // Wrapper, generated by the engine. The arguments are pointers to the values.
  using WrappedMainFunc = void (*)(void **);
  // The first arg is a pointer to a context.
  using CtxMainFunc = void (*)(void *, void **);
  const std::variant<WrappedMainFunc, CtxMainFunc> mainFunc;
  const uint64_t outArgsMask;
  const uint8_t argCount;

  CachedEngine(std::unique_ptr<::gc::JitEngine> engine,
               std::variant<WrappedMainFunc, CtxMainFunc> mainFunc,
               uint64_t outArgsMask, uint8_t argCount,
               void (*destructor)(::gc::JitEngine &) = nullptr)
      : engine(std::move(engine)), mainFunc(mainFunc), outArgsMask(outArgsMask),
        argCount(argCount), destructor(destructor) {}
  ~CachedEngine() {
    if (destructor) destructor(*engine);
  }

  bool isCtxMain() const {
    return std::holds_alternative<CtxMainFunc>(mainFunc);
  }

private:
  void (*destructor)(::gc::JitEngine &);
};

struct Key {
  Key(std::array<uint8_t, 20> hash) : mapKey{.hash = hash, .tag = 1} {}

  SmallString<40> &hex();

private:
  struct MapKey {
    std::array<uint8_t, 20> hash;
    uint8_t tag = 1;
    bool operator==(const MapKey &other) const {
      return hash == other.hash && tag == other.tag;
    }
  } mapKey;
  friend struct Cache;
  friend struct llvm::DenseMapInfo<Key::MapKey>;
  SmallString<40> hexHash;

  Key(std::array<uint8_t, 20> hash, uint8_t tag)
      : mapKey{.hash = hash, .tag = tag} {}
};

inline bool isFileCacheEnabled() {
  constexpr bool offByDefault =
#ifdef GC_FILE_CACHE_DEFAULT_OFF
      true;
#else
      false;
#endif
  static bool enabled =
      !mlir::gc::misc::getEnv("GC_FILE_CACHE_OFF", offByDefault);
  return enabled;
}

inline Key getKey(ModuleOp mod, ArrayRef<uint8_t> salt = {}) {
  llvm::SHA1 key;
  std::string ir;
  llvm::raw_string_ostream os(ir);
  mod.print(os);
  key.update(GC_VERSION_STRING);
  key.update(ir);
  key.update(salt);
  key.final();
  return {key.result()};
}

// Fn is of type SymbolMap (&)(MangleAndInterner).
template <typename Fn>
std::shared_ptr<const CachedEngine>
load(Key &key, Fn &&registerSymbols,
     void (*destructor)(::gc::JitEngine &) = nullptr,
     llvm::ArrayRef<StringRef> sharedLibPaths = {});

llvm::Expected<std::shared_ptr<const CachedEngine>>
save(Key &key, std::unique_ptr<ExecutionEngine> engine, StringRef mainFuncName,
     bool isCtxMain, uint64_t outArgsMask, uint8_t argCount,
     llvm::SmallDenseMap<StringRef, std::variant<ModuleOp, StringAttr>>
         &dumpModules,
     void (*destructor)(::gc::JitEngine &) = nullptr);
} // namespace mlir::gc::cache
